name: Build Component in Native Environment

on:
  pull_request:
    branches: [ develop ]
    paths: ['**/*.c', '**/*.cpp', '**/*.cc', '**/*.cxx', '**/*.h', '**/*.hpp', '**/*.sh']

jobs:
  build-meminsight-on-pr:
    name: Build xMemInsight component in GitHub RDKCentral
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rdkcentral/docker-device-mgt-service-test/native-platform:1.6.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Dependencies
        run: |
          apt-get install -y libtool

      - name: Build the component
        run: |
          sh cov_build.sh --clean # Clean build to ensure no stale artifacts
          sh cov_build.sh # Build the component

      # - name: Run tests (optional)
      #   run: |
      #     # If you have tests to run after building, you can add them here
      #     # For example:
      #     make test
